# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5391516886efa5587cb4c2aa4bd5e028398286c5bace9072df0293b50a9a99568f4d3920530ccb18887d2b209a1d4f22813f1356e9b3d3c01a79a02371fd40b0

test:
  secret_key_base: 9af4584795ae5689345d7ec738722a54cd7f343018d809f67f3ed57b6fd4d7f878b5277e0f79d478390bb11d1c782c20f36af5026a8cdfd2bbe2e5a15273b22e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
